version: '2'

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    networks:
      main:
        ipv4_address: 172.18.1.31
    restart: always
  docs:
    build:
      context: ./docs
      dockerfile: ./Dockerfile
    networks:
      main:
        ipv4_address: 172.18.1.32
    restart: always

networks:
  main:
    external:
      name: main
